config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/message'
  get 'home/move_player'
  root 'home#main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fruit.rb
# frozen_string_literal: true

require 'securerandom'

class Fruit
  attr_accessor :id
  attr_accessor :x
  attr_accessor :y

  def initialize
    game = Game.instance

    self.id = SecureRandom.uuid
    self.x = rand(0..game.state.screen.width)
    self.y = rand(0..game.state.screen.height)
  end

  def to_h
    hash = {}
    instance_variables.each { |var| hash[var.to_s.delete('@')] = instance_variable_get(var) }
    hash
  end
end

app/models/game.rb
# frozen_string_literal: true

# There's only one Game instance which will control all state.
# This limitation is aimed at a Proof of Concept (PoC) only, as
# in the future there could be multiple games
class Game
  include Singleton

  attr_accessor :state
  attr_accessor :fruit_interval

  def initialize
    self.state = State.new
    @fruit_interval = 5

    Thread.new do
      loop do
        add_fruit
        sleep @fruit_interval.to_i
      end
    end
  end

  def add_fruit
    if get_players.empty?
      get_fruits.each do |_k, _v|
        get_fruits.delete(_k)
      end
      return
    end

    fruit = Fruit.new
    state.addFruit(fruit)
    puts "> Creating a new fruit: #{fruit}"
    ActionCable.server.broadcast 'game_channel', { type: 'add-fruit', game: to_h }
    # dump_fruits
  end

  def get_players
    state.players
  end

  def get_fruits
    state.fruits
  end

  def dump_fruits
    puts '-> List of fruits'
    get_fruits.each { |_k, v| puts "Fruit: #{v.to_h}" }
  end

  def add_player(player_id)
    player = Player.new(player_id,
                        "Player #{get_players.count + 1}",
                        rand(0..state.screen.width),
                        rand(0..state.screen.height))

    state.addPlayer(player)

    puts "> Subscribe: #{player.to_h}"
    dump_players
  end

  def dump_players
    puts '-> List of online Players'
    get_players.each { |_k, v| puts "Player: #{v.to_h}" }
  end

  def remove_player(_player_id)
    player = get_players[_player_id]
    state.removePlayer(player)

    puts "> Unsubscribe: #{player.to_h}"
    # dump_players
  end

  def remove_fruit(fruit)
    # fruit = get_fruits[fruit] if fruit.is_a(String)
    state.removeFruit(fruit)
    puts "> Fruit removed: #{fruit.id}"
  end

  def to_h
    hash = {}
    instance_variables.each { |var| hash[var.to_s.delete('@')] = instance_variable_get(var) }
    hash
  end

  def move_player(command)
    method = command['content']['keyPressed']
    player_id = command['current_player_id']
    player = get_players[player_id]

    # equivalent to titleize, downcase, and replace spaces by underscore
    # ex:
    # method = "ArrowUp".tableize.singularize
    #  => "arrow_up"
    if method.present?
      method = method.tableize.singularize
      if respond_to? method
        ActionCable.server.broadcast 'game_channel', { type: 'move-player', game: to_h }
        public_send(method, player)
        check_for_fruit_collision(player)
      end
    end
  end

  def check_for_fruit_collision(_player)
    get_fruits.each do |_k, fruit|
      next unless _player.x == fruit.x && _player.y == fruit.y

      puts "> Deleting fruit #{fruit.id} player: #{_player.id}"
      remove_fruit(fruit)
      _player.score = _player.score + 1
    end
  end

  def arrow_up(player)
    puts '> Arrow Up '
    player.y = mod(state.screen.height, player.y - 1)
  end

  def arrow_right(player)
    puts '> Arrow Right'
    player.x = mod(state.screen.width, player.x + 1)
  end

  def arrow_down(player)
    puts '> Arrow Down'
    player.y = mod(state.screen.height, player.y + 1)
  end

  def arrow_left(player)
    puts '> Arrow Left'
    player.x = mod(state.screen.width, player.x - 1)
  end

  private

  def mod(x, y)
    ((y % x) + x) % x
  end
end

app/models/player.rb
# frozen_string_literal: true

class Player
  attr_accessor :id
  attr_accessor :name
  attr_accessor :x
  attr_accessor :y
  attr_accessor :score

  def initialize
    self.id = ''
    self.name = ''
    self.x = 0
    self.y = 0
    self.score = 0
  end

  def initialize(id = 'n/a', name = '', x = 0, y = 0)
    self.id = id
    self.name = name
    self.x = x
    self.y = y
    self.score = 0
  end

  def to_h
    hash = {}
    instance_variables.each { |var| hash[var.to_s.delete('@')] = instance_variable_get(var) }
    hash
  end
end

app/models/screen.rb
# frozen_string_literal: true

class Screen
  attr_accessor :width
  attr_accessor :height

  def initialize
    self.width = 10
    self.height = 10
  end

  def to_h
    hash = {}
    instance_variables.each { |var| hash[var.to_s.delete('@')] = instance_variable_get(var) }
    hash
  end
end

app/models/state.rb
# frozen_string_literal: true

class State
  attr_accessor :players
  attr_accessor :fruits
  attr_accessor :screen

  def initialize
    self.players = {}
    self.fruits = {}
    self.screen = Screen.new
  end

  def addPlayer(player)
    players[player.id] = player
  end

  def removePlayer(player)
    players.delete(player.id)
  end

  def addFruit(fruit)
    fruits[fruit.id] = fruit
  end

  def removeFruit(fruit)
    fruits.delete(fruit.id)
  end

  def to_h
    hash = {}
    instance_variables.each { |var| hash[var.to_s.delete('@')] = instance_variable_get(var) }
    hash
  end
end

app/models/string.rb
class String
  def to_hash(arr_sep=',', key_sep=':')
    array = self.split(arr_sep)
    hash = {}

    array.each do |e|
      key_value = e.split(key_sep)
      hash[key_value[0]] = key_value[1]
    end

    return hash
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def main; end

  def message
    p1 = Player.new
    p1.id = 'id-p1'
    p1.name = 'Rogerio'
    p1.x = 3
    p1.y = 2

    game = Game.instance
    game.state.addPlayer(p1)
    ActionCable.server.broadcast 'game_channel', { message: 'Hello from the controller', game: game.to_h }
  end

  # def move_player(command); end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/main.html.erb
<% stylesheet_pack_tag 'application' %>

<div class="center alert alert-warning" id="message">Empty
</div>

<div class="container-fluid">
  <h1>Primeiro Jogo - Rails Impl.</h1>
  <br>
  <div class="row">
    <article class="col-md-7">
      <canvas id='screen' height="10" width="10"></canvas>
    </article>
    <aside class="col-md-5 right-space">
      <%# <div class="row "> %>
        <%# <%= link_to 'Click here', home_message_path, remote: true %> 
      <%# </div> %>
      <div class="row">
        <div class="col-md-6" style="padding-left:0; margin-left:0">
          <div class="btn-group" data-toggle="buttons">
            <label class="btn btn-primary active">
              <input type="checkbox" name="" id="chk_framerate" onclick="" autocomplete="off"> Exibir <i>Framerate</i>
            </label>
          </div>
        </div>
        <div class="col-md-6">
          <div style="text-align:right" id="framerate">n/a</div>
        </div>
      </div>
      <%# <div class="row">
        <label for="name" class="name">Nome do Jogador (opcional)</label><br/>
        <input type="text" id='name' class="form-control"/>
      </div> %>
      <div class="row">&nbsp;</div>
      <div class="row">
        <table class="table table-striped " id="score-table">
          <thead>
            <th>Nome</th>
            <th>Channel Id</th>
            <th>Count</th>
          </thead>
          <tbody id='score-body'>
            <tr>
              <td>Nome</td>
              <td>xxxx</td>
              <td class="right">3</td>
            </tr>
            <tr>
              <td>Nome</td>
              <td>xxxx</td>
              <td class="right">3</td>
            </tr>
            <tr>
              <td>Nome</td>
              <td>xxxx</td>
              <td class="right">3</td>
            </tr>            
          </tbody>
          <%# <tfoot>
            <tr>
              <td colspan="2">Total colisões</td>
              <td class="bold right"><span id="total_colisions">123</span></td>
            </tr>
            <tr>
              <td>Melhor Jogador</td>
              <td colspan="2" class="bold right"><span id="best_player">Nome (xx colisions)</span></td>
            </tr>
          </tfoot> %>
        </table>
      </div>
    </aside>
  </div>
</div>

<footer>
<h4>Rails implementation for Filipe Dechamps' proposal of a multiplayer online game</h4>
<p>
Originally written in Javascript / Node.Js, I've implemented this simpler version for learning purposes.<br>
You can find this source code in my <a href="https://github.com/rnasc/primeiro-jogo">Github page</a><br>
You can find Filipe's proposal in his <a href="https://www.youtube.com/watch?v=0sTfIZvjYJk&list=PLMdYygf53DP5SVQQrkKCVWDS0TwYLVitL">youtube channel</a></p>
</footer>

<script>
  $(document).on('turbolinks:load', function () {
    fade()

    function fade() {
      $(".alert").fadeTo(2000, 500).slideUp(500, function(){
          $(".alert").slideUp(500);
      });
    }
  })      
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Channel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>      
    <%= yield %>
  </body>
</html>